### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by msabramo** [justinabrahms/dictshield-views#1]
All I see in the repo is a `README.md`.

**Comment by justinabrahms** [comment]
I didn't actually get much response from others as to if it was a good idea or not. I determined that if others didn't find it useful, I wouldn't write it. I don't actually have the opportunity to use dictshield at work and my personal projects are already piling up. :) I'll probably leave this around in case anyone wants to pick it up, but as it stands, its just an idea.
